-- MySQL Script generated by MySQL Workbench
-- Sun Apr  4 16:01:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `ID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `specialisation` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `hospital_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_doctor_hospital1_idx` (`hospital_ID` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_hospital1`
    FOREIGN KEY (`hospital_ID`)
    REFERENCES `mydb`.`hospital` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital` (
  `ID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `doctor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_hospital_doctor1_idx` (`doctor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_doctor1`
    FOREIGN KEY (`doctor_ID`)
    REFERENCES `mydb`.`doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HDIKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HDIKA` (
  `AMKA` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`AMKA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`potential_patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`potential_patient` (
  `AMKA` INT NOT NULL,
  `medical_history` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AMKA`),
  CONSTRAINT `fk_visitor_HDIKA1`
    FOREIGN KEY (`AMKA`)
    REFERENCES `mydb`.`HDIKA` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital_visit` (
  `hospital_ID` INT NOT NULL,
  `visitor_AMKA` INT NOT NULL,
  `doctor_ID` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`hospital_ID`, `visitor_AMKA`, `doctor_ID`, `date`),
  INDEX `fk_hospital_visit_hospital1_idx` (`hospital_ID` ASC) VISIBLE,
  INDEX `fk_hospital_visit_visitor1_idx` (`visitor_AMKA` ASC) VISIBLE,
  INDEX `fk_hospital_visit_doctor1_idx` (`doctor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_visit_hospital1`
    FOREIGN KEY (`hospital_ID`)
    REFERENCES `mydb`.`hospital` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospital_visit_visitor1`
    FOREIGN KEY (`visitor_AMKA`)
    REFERENCES `mydb`.`potential_patient` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospital_visit_doctor1`
    FOREIGN KEY (`doctor_ID`)
    REFERENCES `mydb`.`doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`covid19_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`covid19_test` (
  `type_name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`type_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital_wing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital_wing` (
  `ID` INT NOT NULL,
  `hospital_ID` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `bed_no` INT NOT NULL,
  `medical_specialisation` VARCHAR(45) NOT NULL,
  `covid_specified` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `hospital_ID`),
  INDEX `fk_hospital_wing_hospital1_idx` (`hospital_ID` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_wing_hospital1`
    FOREIGN KEY (`hospital_ID`)
    REFERENCES `mydb`.`hospital` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `room_no` INT NOT NULL,
  `beds_no` INT NOT NULL,
  `hospital_wing_ID` INT NOT NULL,
  `hospital_wing_hospital_ID` INT NOT NULL,
  PRIMARY KEY (`room_no`, `hospital_wing_ID`, `hospital_wing_hospital_ID`),
  INDEX `fk_room_hospital_wing1_idx` (`hospital_wing_ID` ASC, `hospital_wing_hospital_ID` ASC) VISIBLE,
  CONSTRAINT `fk_room_hospital_wing1`
    FOREIGN KEY (`hospital_wing_ID` , `hospital_wing_hospital_ID`)
    REFERENCES `mydb`.`hospital_wing` (`ID` , `hospital_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor_works_at_hospital_wing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor_works_at_hospital_wing` (
  `doctor_ID` INT NOT NULL,
  `hospital_wing_ID` INT NOT NULL,
  `hospital_wing_hospital_ID` INT NOT NULL,
  `working_date` DATE NOT NULL,
  PRIMARY KEY (`doctor_ID`, `hospital_wing_ID`, `hospital_wing_hospital_ID`, `working_date`),
  INDEX `fk_doctor_has_hospital_wing_hospital_wing1_idx` (`hospital_wing_ID` ASC, `hospital_wing_hospital_ID` ASC) VISIBLE,
  INDEX `fk_doctor_has_hospital_wing_doctor1_idx` (`doctor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_has_hospital_wing_doctor1`
    FOREIGN KEY (`doctor_ID`)
    REFERENCES `mydb`.`doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_has_hospital_wing_hospital_wing1`
    FOREIGN KEY (`hospital_wing_ID` , `hospital_wing_hospital_ID`)
    REFERENCES `mydb`.`hospital_wing` (`ID` , `hospital_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EODY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EODY` (
  `testID` INT NOT NULL,
  `covid19_test_type_name` VARCHAR(10) NOT NULL,
  `date` DATE NOT NULL,
  `results` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`testID`),
  INDEX `fk_EODY_covid19_test1_idx` (`covid19_test_type_name` ASC) VISIBLE,
  CONSTRAINT `fk_EODY_covid19_test1`
    FOREIGN KEY (`covid19_test_type_name`)
    REFERENCES `mydb`.`covid19_test` (`type_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`covid_exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`covid_exam` (
  `testID` INT NOT NULL,
  `hospital_ID` INT NOT NULL,
  `visitor_AMKA` INT NOT NULL,
  `doctor_ID` INT NOT NULL,
  PRIMARY KEY (`testID`, `hospital_ID`, `visitor_AMKA`, `doctor_ID`),
  INDEX `fk_covid_exam_EODY1_idx` (`testID` ASC) VISIBLE,
  CONSTRAINT `fk_examination_hospital_visit1`
    FOREIGN KEY (`hospital_ID` , `visitor_AMKA` , `doctor_ID`)
    REFERENCES `mydb`.`hospital_visit` (`hospital_ID` , `visitor_AMKA` , `doctor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_covid_exam_EODY1`
    FOREIGN KEY (`testID`)
    REFERENCES `mydb`.`EODY` (`testID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inpatient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inpatient` (
  `AMKA` INT NOT NULL,
  `room_no` INT NOT NULL,
  `room_hospital_wing_ID` INT NOT NULL,
  `hospital_ID` INT NOT NULL,
  `recent_encounters_AMKA` INT NULL,
  INDEX `fk_inpatient_room1_idx` (`room_no` ASC, `room_hospital_wing_ID` ASC, `hospital_ID` ASC) VISIBLE,
  PRIMARY KEY (`AMKA`),
  INDEX `fk_inpatient_visitor2_idx` (`recent_encounters_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_inpatient_room1`
    FOREIGN KEY (`room_no` , `room_hospital_wing_ID` , `hospital_ID`)
    REFERENCES `mydb`.`room` (`room_no` , `hospital_wing_ID` , `hospital_wing_hospital_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inpatient_visitor1`
    FOREIGN KEY (`AMKA`)
    REFERENCES `mydb`.`potential_patient` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inpatient_visitor2`
    FOREIGN KEY (`recent_encounters_AMKA`)
    REFERENCES `mydb`.`potential_patient` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`in_hospital_exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`in_hospital_exam` (
  `ID` INT NOT NULL,
  `date` DATE NOT NULL,
  `summary` VARCHAR(45) NOT NULL,
  `results` VARCHAR(45) NOT NULL,
  `inpatient_AMKA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_in_hospital_exam_inpatient1_idx` (`inpatient_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_in_hospital_exam_inpatient1`
    FOREIGN KEY (`inpatient_AMKA`)
    REFERENCES `mydb`.`inpatient` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medical_examination_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medical_examination_center` (
  `ID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`covid19_exam_in_med_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`covid19_exam_in_med_center` (
  `testID` INT NOT NULL,
  `potential_patient_AMKA` INT NOT NULL,
  `medical_examination_center_ID` INT NOT NULL,
  PRIMARY KEY (`testID`, `potential_patient_AMKA`, `medical_examination_center_ID`),
  INDEX `fk_potential_patient_has_medical_examination_center_medical_idx` (`medical_examination_center_ID` ASC) VISIBLE,
  INDEX `fk_potential_patient_has_medical_examination_center_potenti_idx` (`potential_patient_AMKA` ASC) VISIBLE,
  INDEX `fk_covid19_exam_in_med_center_EODY1_idx` (`testID` ASC) VISIBLE,
  CONSTRAINT `fk_potential_patient_has_medical_examination_center_potential1`
    FOREIGN KEY (`potential_patient_AMKA`)
    REFERENCES `mydb`.`potential_patient` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_potential_patient_has_medical_examination_center_medical_e1`
    FOREIGN KEY (`medical_examination_center_ID`)
    REFERENCES `mydb`.`medical_examination_center` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_covid19_exam_in_med_center_EODY1`
    FOREIGN KEY (`testID`)
    REFERENCES `mydb`.`EODY` (`testID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccine_manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccine_manufacturer` (
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `storage_conditions` VARCHAR(45) NOT NULL,
  `tech_used` VARCHAR(45) NOT NULL,
  `monthly_production` INT NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMA` (
  `ID` INT NOT NULL,
  `EMA_aproved` VARCHAR(5) NOT NULL,
  `aproval_date` DATE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccine` (
  `name` VARCHAR(45) NOT NULL,
  `dose_no` VARCHAR(45) NOT NULL,
  `EMA_ID` INT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_Vaccine_EMA1_idx` (`EMA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Vaccine_Vaccine_manufacturer1`
    FOREIGN KEY (`name`)
    REFERENCES `mydb`.`Vaccine_manufacturer` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaccine_EMA1`
    FOREIGN KEY (`EMA_ID`)
    REFERENCES `mydb`.`EMA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`storage_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`storage_company` (
  `ID` INT NOT NULL,
  `associated_manufacturer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_storage_company_Vaccine_manufacturer1_idx` (`associated_manufacturer` ASC) VISIBLE,
  CONSTRAINT `fk_storage_company_Vaccine_manufacturer1`
    FOREIGN KEY (`associated_manufacturer`)
    REFERENCES `mydb`.`Vaccine_manufacturer` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccine_batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine_batch` (
  `ID` INT NOT NULL,
  `manufacturer_name` VARCHAR(45) NOT NULL,
  `production_date` DATE NOT NULL,
  `vaccine_amount` INT NOT NULL,
  `destination_country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `manufacturer_name`),
  INDEX `fk_vaccine_batch_Vaccine_manufacturer1_idx` (`manufacturer_name` ASC) VISIBLE,
  CONSTRAINT `fk_vaccine_batch_Vaccine_manufacturer1`
    FOREIGN KEY (`manufacturer_name`)
    REFERENCES `mydb`.`Vaccine_manufacturer` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccination_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccination_center` (
  `type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stored_batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stored_batch` (
  `storage_company_ID` INT NOT NULL,
  `vaccine_batch_ID` INT NOT NULL,
  `vaccine_batch_manufacturer_name` VARCHAR(45) NOT NULL,
  `storage_conditions` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`storage_company_ID`, `vaccine_batch_ID`, `vaccine_batch_manufacturer_name`),
  INDEX `fk_storage_company_has_vaccine_batch_vaccine_batch1_idx` (`vaccine_batch_ID` ASC, `vaccine_batch_manufacturer_name` ASC) VISIBLE,
  INDEX `fk_storage_company_has_vaccine_batch_storage_company1_idx` (`storage_company_ID` ASC) VISIBLE,
  CONSTRAINT `fk_storage_company_has_vaccine_batch_storage_company1`
    FOREIGN KEY (`storage_company_ID`)
    REFERENCES `mydb`.`storage_company` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_storage_company_has_vaccine_batch_vaccine_batch1`
    FOREIGN KEY (`vaccine_batch_ID` , `vaccine_batch_manufacturer_name`)
    REFERENCES `mydb`.`vaccine_batch` (`ID` , `manufacturer_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital_is_vaccination_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital_is_vaccination_center` (
  `hospital_ID` INT NOT NULL,
  `hospita_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`hospital_ID`, `hospita_type`),
  INDEX `fk_hospital_has_vaccination_center_vaccination_center1_idx` (`hospita_type` ASC) VISIBLE,
  INDEX `fk_hospital_has_vaccination_center_hospital1_idx` (`hospital_ID` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_has_vaccination_center_hospital1`
    FOREIGN KEY (`hospital_ID`)
    REFERENCES `mydb`.`hospital` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospital_has_vaccination_center_vaccination_center1`
    FOREIGN KEY (`hospita_type`)
    REFERENCES `mydb`.`vaccination_center` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`med_exam_is_vacc_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`med_exam_is_vacc_center` (
  `medical_examination_center_ID` INT NOT NULL,
  `center_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`medical_examination_center_ID`, `center_type`),
  INDEX `fk_medical_examination_center_has_vaccination_center_vaccin_idx` (`center_type` ASC) VISIBLE,
  INDEX `fk_medical_examination_center_has_vaccination_center_medica_idx` (`medical_examination_center_ID` ASC) VISIBLE,
  CONSTRAINT `fk_medical_examination_center_has_vaccination_center_medical_1`
    FOREIGN KEY (`medical_examination_center_ID`)
    REFERENCES `mydb`.`medical_examination_center` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medical_examination_center_has_vaccination_center_vaccinat1`
    FOREIGN KEY (`center_type`)
    REFERENCES `mydb`.`vaccination_center` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccination` (
  `ID` INT NOT NULL,
  `AMKA` INT NOT NULL,
  `dose1_date` VARCHAR(45) NOT NULL,
  `dose2_date` VARCHAR(45) NOT NULL,
  `hospital_ID` INT NULL,
  `hospita_type` VARCHAR(10) NULL,
  `medical_examination_center_ID` INT NULL,
  `center_type` VARCHAR(10) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Vaccination_HDIKA1_idx` (`AMKA` ASC) VISIBLE,
  INDEX `fk_Vaccination_hospital_is_vaccination_center1_idx` (`hospital_ID` ASC, `hospita_type` ASC) VISIBLE,
  INDEX `fk_Vaccination_med_exam_is_vacc_center1_idx` (`medical_examination_center_ID` ASC, `center_type` ASC) VISIBLE,
  CONSTRAINT `fk_Vaccination_HDIKA1`
    FOREIGN KEY (`AMKA`)
    REFERENCES `mydb`.`HDIKA` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaccination_hospital_is_vaccination_center1`
    FOREIGN KEY (`hospital_ID` , `hospita_type`)
    REFERENCES `mydb`.`hospital_is_vaccination_center` (`hospital_ID` , `hospita_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaccination_med_exam_is_vacc_center1`
    FOREIGN KEY (`medical_examination_center_ID` , `center_type`)
    REFERENCES `mydb`.`med_exam_is_vacc_center` (`medical_examination_center_ID` , `center_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`batch_to_hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`batch_to_hospital` (
  `storage_company_ID` INT NOT NULL,
  `stored_batch_vaccine_batch_ID` INT NOT NULL,
  `manufacturer_name` VARCHAR(45) NOT NULL,
  `hospital_ID` INT NOT NULL,
  `hospita_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`storage_company_ID`, `stored_batch_vaccine_batch_ID`, `manufacturer_name`, `hospital_ID`, `hospita_type`),
  INDEX `fk_hospital_is_vacc_center_has_stored_batch_stored_batch1_idx` (`storage_company_ID` ASC, `stored_batch_vaccine_batch_ID` ASC, `manufacturer_name` ASC) VISIBLE,
  INDEX `fk_batch_to_hospital_hospital_is_vaccination_center1_idx` (`hospital_ID` ASC, `hospita_type` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_is_vacc_center_has_stored_batch_stored_batch1`
    FOREIGN KEY (`storage_company_ID` , `stored_batch_vaccine_batch_ID` , `manufacturer_name`)
    REFERENCES `mydb`.`stored_batch` (`storage_company_ID` , `vaccine_batch_ID` , `vaccine_batch_manufacturer_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batch_to_hospital_hospital_is_vaccination_center1`
    FOREIGN KEY (`hospital_ID` , `hospita_type`)
    REFERENCES `mydb`.`hospital_is_vaccination_center` (`hospital_ID` , `hospita_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`batch_to_exam_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`batch_to_exam_center` (
  `stored_batch_storage_company_ID` INT NOT NULL,
  `stored_batch_vaccine_batch_ID` INT NOT NULL,
  `manufacturer_name` VARCHAR(45) NOT NULL,
  `examination_center_ID` INT NOT NULL,
  `center_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`stored_batch_storage_company_ID`, `stored_batch_vaccine_batch_ID`, `manufacturer_name`, `examination_center_ID`, `center_type`),
  INDEX `fk_med_exam_is_vacc_center_has_stored_batch_stored_batch1_idx` (`stored_batch_storage_company_ID` ASC, `stored_batch_vaccine_batch_ID` ASC, `manufacturer_name` ASC) VISIBLE,
  INDEX `fk_batch_to_exam_center_med_exam_is_vacc_center1_idx` (`examination_center_ID` ASC, `center_type` ASC) VISIBLE,
  CONSTRAINT `fk_med_exam_is_vacc_center_has_stored_batch_stored_batch1`
    FOREIGN KEY (`stored_batch_storage_company_ID` , `stored_batch_vaccine_batch_ID` , `manufacturer_name`)
    REFERENCES `mydb`.`stored_batch` (`storage_company_ID` , `vaccine_batch_ID` , `vaccine_batch_manufacturer_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batch_to_exam_center_med_exam_is_vacc_center1`
    FOREIGN KEY (`examination_center_ID` , `center_type`)
    REFERENCES `mydb`.`med_exam_is_vacc_center` (`medical_examination_center_ID` , `center_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
